import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // Recording...
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admina');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('dmin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Job' }).locator('i').click();
  await page.getByRole('menuitem', { name: 'Job Titles' }).click();
  await page.getByRole('row', { name: ' QA Engineer  ' }).locator('label i').click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('QA Tester');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Responsible for manual and automated testing.');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Responsible for manual and automated testing.Note: This is a test job title');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Responsible for manual and automated testing. Note: This is a test job title');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('Shift+ArrowLeft');
  await page.getByRole('textbox', { name: 'Type description here' }).press('ControlOrMeta+x');
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Responsible for manual and automated testing. ');
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).click({
    button: 'right'
  });
  await page.getByRole('textbox', { name: 'Add note' }).fill('Note: This is a test job title');
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).dblclick();
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).fill('Note: This is a test job title.');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Add note' }).fill('This is a test job title.');
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('OrangeHRM OS 5.7© 2005 - 2025').click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Save' }).click();
});